### ISSUE TITLE
Kısa soru🙂

### ISSUE THREAD

**Issue by ghost** [Eren5960/DebugCommand#1]
Seylamu aleykum 

Bazı Alman beni reddetmek istedim çünkü benim sunucu bir geliştirici arıyorum ben tam olarak aynı dil ve Türkçe konuşan bir kardeş sormak istedim Eğer eklenti uymuyor düşünüyorsanız o zaman çok üzgünüm ama ben sadece bana yardımcı olacak bir geliştirici arıyorum. 

Iyi günler dostum

**Comment by xerenahmed** [comment]
@DragonfireHD i already server (StormGames.net)
